# Generated by Django 4.1.3 on 2023-08-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_is_paid_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='saved_items',
        ),
    ]
